### ISSUE TITLE
样式和js为啥后台找不到

### ISSUE THREAD

**Issue by W7851167** [e282486518/yii2admin#13]
为啥前台有css和js，后台找不到，多了一层admin/
这个没找到在哪儿控制的 
这个是前台的样式地址/assets/584fb616/global/plugins/ccslider/css/style.css
这个是后台的样式地址/admin/assets/584fb616/global/css/plugins-md.min.css
多了一层/admin/  去掉就好了，这个是在哪里控制的？

**Comment by e282486518** [comment]
.env文件中有配置
FRONTEND_URL     = /
BACKEND_URL      = /admin
API_URL          = /api
STORAGE_URL      = /storage
配合Apache和Nginx中的重写可以完成
