### ISSUE TITLE
安装后访问出现错误

### ISSUE THREAD

**Issue by rockyhu** [e282486518/yii2admin#3]
作者您好，您的这套程序非常的不错，值得我去学习，但是在安装项目的过程中，遇到了如下问题，还请作者指明问题的所在！

具体的错误提示如下：
Warning: require(/Applications/XAMPP/xamppfiles/htdocs/yii2admin/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php): failed to open stream: No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/yii2admin/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/Applications/XAMPP/xamppfiles/htdocs/yii2admin/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php' (include_path='.:/Applications/XAMPP/xamppfiles/lib/php') in /Applications/XAMPP/xamppfiles/htdocs/yii2admin/vendor/composer/autoload_real.php on line 66

环境配置如下：
1、项目文件yii2admin放置在/Applications/XAMPP/htdocs/文件夹下；
2、Apache配置：
<VirtualHost *:80>
    ServerAdmin webmaster@www.yii2admin.com
    DocumentRoot "/Applications/XAMPP/htdocs/yii2admin/frontend/web/"
    ServerName www.yii2admin.com
    <Directory />
        Options FollowSymLinks
        AllowOverride All
        Order deny,allow
        allow from all
    </Directory>
    ErrorLog "logs/www.yii2admin.com-error_log"
    CustomLog "logs/www.yii2admin.com-access_log" common
</VirtualHost>

<VirtualHost *:80>
    ServerAdmin webmaster@admin.yii2admin.com
    DocumentRoot "/Applications/XAMPP/htdocs/yii2admin/backend/web/"
    ServerName admin.yii2admin.com
    <Directory />
        Options FollowSymLinks
        AllowOverride All
        Order deny,allow
        allow from all
    </Directory>
    ErrorLog "logs/admin.yii2admin.com-error_log"
    CustomLog "logs/admin.yii2admin.com-access_log" common
</VirtualHost>

<VirtualHost *:80>
    ServerAdmin webmaster@storage.yii2admin.com
    DocumentRoot "/Applications/XAMPP/htdocs/yii2admin/storage/web/"
    ServerName storage.yii2admin.com
    <Directory />
        Options FollowSymLinks
        AllowOverride All
        Order deny,allow
        allow from all
    </Directory>
    ErrorLog "logs/storage.yii2admin.com-error_log"
    CustomLog "logs/storage.yii2admin.com-access_log" common
</VirtualHost>

3、hosts文件设置
#Yii2 sample application
127.0.0.1 www.yii2admin.com
127.0.0.1 admin.yii2admin.com
127.0.0.1 torage.yii2admin.com

麻烦作者您提醒问题出在哪里？应该如何去解决这个问题？谢谢！

**Comment by e282486518** [comment]
这个应该是composer安装依赖时有依赖没有安装成功。建议执行composer update试试。

**Comment by rockyhu** [comment]
您好，当我在项目文件夹下执行composer install命令时，提示如下错误，应该如何解决？谢谢！

`rockyhudeMacBook-Pro:yii2admin rockyhu$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for jeremykendall/php-domain-parser 3.0.0 -> satisfiable by jeremykendall/php-domain-parser[3.0.0].
    - jeremykendall/php-domain-parser 3.0.0 requires ext-intl * -> the requested PHP extension intl is missing from your system.
  Problem 2
    - Installation request for league/uri 4.2.1 -> satisfiable by league/uri[4.2.1].
    - league/uri 4.2.1 requires ext-intl * -> the requested PHP extension intl is missing from your system.
  Problem 3
    - league/uri 4.2.1 requires ext-intl * -> the requested PHP extension intl is missing from your system.
    - trntv/yii2-glide 1.1.0 requires league/uri ^4.1 -> satisfiable by league/uri[4.2.1].
    - Installation request for trntv/yii2-glide 1.1.0 -> satisfiable by trntv/yii2-glide[1.1.0].

`

**Comment by rockyhu** [comment]
您好，这个问题解决了，谢谢您的反馈！
