### ISSUE TITLE
安装时报错，执行composer update 提示没有包

### ISSUE THREAD

**Issue by sowork** [e282486518/yii2admin#4]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2 2.0.x-dev requires bower-asset/yii2-pjax ~2.0.1 -> no matching package found.
    - yiisoft/yii2 dev-master requires bower-asset/yii2-pjax ~2.0.1 -> no matching package found.
    - yiisoft/yii2 2.0.9 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.8 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.7 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.6 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.10 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> no matching package found.
    - Installation request for yiisoft/yii2 >=2.0.6 -> satisfiable by yiisoft/yii2[2.0.10, 2.0.6, 2.0.7, 2.0.8, 2.0.9, dev-master, 2.0.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by e282486518** [comment]
composer self-update 更新一下composer试试
不行在更新一下 composer global require "fxp/composer-asset-plugin:^1.2.0"

**Comment by sowork** [comment]
Thanks

**Comment by leo0o** [comment]
![image](https://cloud.githubusercontent.com/assets/5572910/23698693/7462a2a4-0427-11e7-9de6-e95b8185c2d1.png)
你好，两个方法都试过了，还是出现这种问题

**Comment by e282486518** [comment]
貌似github的oauth token有问题。新建一个试试

**Comment by leo0o** [comment]
@e282486518   我sb了。。。好了，谢谢啦

**Comment by W7851167** [comment]
composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Killed
这是为啥 ？ Killed是什么意思？

**Comment by e282486518** [comment]
可以提供完整截图不？

**Comment by W7851167** [comment]
在另一台虚拟机上搞定了，这个好像是因为我的虚拟机空间内存太小造成的，现在是可以访问了

**Comment by yang-xd** [comment]
The "extra.asset-installer-paths" option is deprecated, use the "config.fxp-asset.installer-paths" option
Loading composer repositories with package information
Updating dependencies (including require-dev)
Reading bower.json of bower-asset/jquery (2.1.0-RC1)
Could not fetch https://api.github.com/repos/jquery/jquery-dist/contents/bower.json?ref=dea4e5fc6c47a27865de65ec6feef3429dbf13b9, please create a GitHub OAuth token to go over the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+SKY-20170708PJQ+2017-08-04+0849
to retrieve a token. It will be stored in "C:/Users/admin/AppData/Roaming/Composer/auth.json" for future use by Composer.
Token (hidden):


  [Composer\Repository\InvalidRepositoryException]
  No valid bower.json was found in any branch or tag of https://github.com/HubSpot/tether.git, could not load a package
  from it.


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

**Comment by e282486518** [comment]
github授权问题? @yang-xd  如果不行可以下载全站打包文件

**Comment by flighter613** [comment]
![_20170804162438](https://user-images.githubusercontent.com/29209997/28990357-8a35d982-7931-11e7-9e9f-8d216d55d1f6.png)
![2](https://user-images.githubusercontent.com/29209997/28990358-8efe8090-7931-11e7-8f6f-a263a00e5074.png)
请教如何解决
