### ISSUE TITLE
SQL问题

### ISSUE THREAD

**Issue by baqianxin** [e282486518/yii2admin#6]
![image](https://cloud.githubusercontent.com/assets/6780391/23539857/d0d7fe98-0018-11e7-8d63-b6c69cfe0b96.png)
`               \ /* 生成child树 *\/`
    `            $groups = static::find()->select(['group'])
                    ->where(['pid'=>$item['id'], 'hide'=>0])
                    ->groupBy(['sort','group'])->orderBy('sort `ASC')->asArray()->column();`

**Comment by baqianxin** [comment]
Database Exception – yii\db\Exception

SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'yii2admin.yii2_menu.sort' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
The SQL being executed was: SELECT `group` FROM `yii2_menu` WHERE (`pid`='68') AND (`hide`=0) GROUP BY `group` ORDER BY `sort`
Error Info: Array
(
    [0] => 42000
    [1] => 1055
    [2] => Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'yii2admin.yii2_menu.sort' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
)

**Comment by e282486518** [comment]
是安装后就出现这个错误，还是修改了某些内容后导致的这个错误？可否重现？

**Comment by baqianxin** [comment]
可以重现，是mysql查询语句的问题，Group 与 Order 共同存在时，有的查询模式需要Group强制包含Order表达式所含字段，加上即可

**Comment by e282486518** [comment]
这条sql语句确实写的不标准，only_full_group_by模式下会有sort不明确导致的问题，谢谢指正。

不过我更倾向于这个，mysql5.5不知道怎么开启这个模式，没有测试，不知道对不对。
```sql
$groups = static::find()->select(['group','min(sort) as sort']) ->where(['pid'=>$item['id'], 'hide'=>0]) ->groupBy(['sort','group'])->orderBy('sortASC')->asArray()->column();
```

**Comment by e282486518** [comment]
$groups = static::find()->select(['group','min(sort) as sort']) ->where(['pid'=>$item['id'], 'hide'=>0]) ->groupBy(['group'])->orderBy('sortASC')->asArray()->column();

**Comment by baqianxin** [comment]
多向你学习
